# Generated by Django 4.0.3 on 2022-04-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_user_answers_author_alter_questions_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='author',
            new_name='ansauthor',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='date',
            new_name='ansdate',
        ),
    ]
