# Generated by Django 4.0.3 on 2022-04-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_author_answers_ansauthor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answers',
        ),
    ]
