# Generated by Django 4.0.3 on 2022-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_answers_ansuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='youranswer',
            field=models.TextField(),
        ),
    ]
