# Generated by Django 4.0.3 on 2022-04-20 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comment_delete_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
